title: Vim Farsi
description: test repo and scapegoat page build for https://vimpersian.github.io/
remote_theme: pages-themes/hacker@v0.2.0
#remote_theme: pages-themes/midnight@v0.2.0
#google_analytics: G-HW0E88QFZ8
#show_downloads: true
